const strings = {
  'en-US': {
    'RECENT DESCRIPTIONS': 'RECENT DESCRIPTIONS',
    'WISH LIST': 'WISH LIST',
    HOME: 'HOME',
    Close: 'Close',
    Search: 'Search',
    Credits: 'Credits',
    'Contact Us': 'Contact Us',
    Support: 'Support',
    'YouDescribe is a project of': 'YouDescribe is a project of',
    'Load more videos': 'Load more videos',
    'Sign in with Google': 'Sign in with Google',
    'All rights reserved': 'All rights reserved',
    'YouDescribe - Audio Description for YouTube Videos': 'YouDescribe - Audio Description for YouTube Videos',
    'Search for a YouTube video. If a video with an audio description matching the search criteria exists, it will be available in the first section. If not, Youtube videos without audio descriptions matching the search criteria will be listed in the second section and requests for any of those videos can be made.': 'Search for a YouTube video. If a video with an audio description matching the search criteria exists, it will be available in the first section. If not, Youtube videos without audio descriptions matching the search criteria will be listed in the second section and requests for any of those videos can be made.',    
  },
  'pt-BR': {
    'RECENT DESCRIPTIONS': 'DESCRIÇÕES RECENTES',
    'WISH LIST': 'LISTA DE DESEJOS',
    HOME: 'INÍCIO',
    Close: 'Fechar',
    Search: 'Busca',
    Credits: 'Créditos',
    'Contact Us': 'Contato',
    Support: 'Suporte',
    'YouDescribe is a project of': 'YouDescribe é um projeto do',
    'Load more videos': 'Carregar mais vídeos',
    'Sign in with Google': 'Entrar com o Google',
    'All rights reserved': 'Todos os direitos reservados',
    'YouDescribe - Audio Description for YouTube Videos': 'YouDescribe - Áudio Descrição para vídeos do YouTube',
    'Search for a YouTube video. If a video with an audio description matching the search criteria exists, it will be available in the first section. If not, Youtube videos without audio descriptions matching the search criteria will be listed in the second section and requests for any of those videos can be made.': 'Busque por um vídeo do YouTube. Se um vídeo com audio descrição for encontrado, ele estará no primeiro bloco. Caso contrário estará no segundo bloco e você poderá solicitar uma audio descrição.',
  },
};

export default strings;
