const strings = {
  'en-US': {
    'RECENT DESCRIPTIONS': 'DESCRIÇÕES RECENTES',
    'WISH LIST': 'LISTA DE DESEJOS',
    HOME: 'INÍCIO',
    Close: 'Fechar',
    Search: 'Busca',
    Credits: 'Créditos',
    'Contact Us': 'Contato',
    Support: 'Suporte',
    'YouDescribe is a project of': 'YouDescribe é um projeto do',
    'Load more videos': 'Carregar mais vídeos',
    'Load more': 'Carregar mais',
    'Sign in with Google': 'Entrar com o Google',
    'All rights reserved': 'Todos os direitos reservados',
    'YouDescribe - Audio Description for YouTube Videos': 'YouDescribe - Áudio Descrição para vídeos do YouTube',
    'Search for a YouTube video. If a video with an audio description matching the search criteria exists, it will be available in the first section. If not, Youtube videos without audio descriptions matching the search criteria will be listed in the second section and requests for any of those videos can be made.': 'Busque por um vídeo do YouTube. Se um vídeo com audio descrição for encontrado, ele estará no primeiro bloco. Caso contrário estará no segundo bloco e você poderá solicitar uma audio descrição.',
    'You must sign in to perform this action': 'Você precisa estar logado para usar esse recurso',
    'You have to be logged in in order to vote': 'Você precisa estar logado para votar',
    'It was impossible to vote. Maybe your session has expired. Try to logout and login again.': 'Não foi possível votar. Tente logar novamente com seu usuário.',
    'YouDescribe - Authoring Tool': 'YouDescribe - Ferramenta de edição',
    'You have to be logged in in order to describe this video': 'Você precisa estar logado para poder descrever este vídeo',
    'Finish using your available record tracks': 'Termine de usar suas trilhas disponíveis',
    'You can just add more tracks when you finish recording the existing one': 'Você só pode adicionar mais trilhas quando terminar de usar as disponíveis',
    'Are you sure you want to remove this track? This action cannot be undone!': 'Você tem certeza que deseja apagar esta trilha? Não será possível desfazer essa ação',
    'Impossible to descrease the start time. It is already 0': 'Não é possível diminuir o tempo de início, pois já está em 0',
    'Impossible to increase the start time more': 'Não é possível aumentar mais o tempo de início',
    'Are you sure you want to change from EXTENDED to INLINE?': 'Você tem certeza que quer mudar de EXTENDIDA para LINEAR?',
    'Are you sure you want to change from INLINE to EXTENDED?': 'Você tem certeza que quer mudar de LINEAR para EXTENDIDA?',
    'You need to be logged in in order to record audio clips': 'Você precisa estar logado para gravar trilhas',
    'You need to stop recording in order to activate any other track': 'Você precisa parar sua gravação para ativar outra trilha',
    'Are you sure you wanna publish this audio description?': 'Você tem certeza que quer publicar essa áudio descrição?',
    'Are you sure you wanna unpublish this audio description?': 'Você tem certeza que quer despublicar essa áudio descrição?',
    'Are you sure you want to delete the audio description? This will remove all recorder tracks and cannot be undone': 'Você tem certeza que quer remover essa áudio descrição? Isso removerá todas as trilhas e não poderá ser desfeito',
    'Authoring is not available on this screen size. Please use a larger screen to add a description': 'A ferramenta de edição não está disponível para o seu tamanho de tela. Use uma resolução maior',
    'Loading': 'Carregando',
    'My descriptions': 'Minhas áudio descrições',
    'Unpublish': 'Despublicar',
    'Publish': 'Publicar',
    'Delete': 'Apagar',
    'Complete remove this audio description': 'Remove esta áudio descrição',
    'Unpublish this audio description for the current video': 'Despublicar esta áudio descrição',
    'Publish the video along with all audio description tracks': 'Publicar este vídeo com áudio descrição',
    'Save notes and labels anytime': 'Grava as notas e os títulos das trilhas',
    'Save': 'Gravar',
    "Add an inline audio description track which plays concurrently with the video's audio": "Adiciona uma trilha linear que irá ser reproduzida junto com o áudio do vídeo",
    'Add an extended audio description track which pauses the video as it plays and then resumes the video when it finishes': 'Adiciona uma trilha extendida que irá pausar o vídeo para ser reproduzida. Assim que terminar, o vídeo voltará a ser reproduzido',
    'YouDescribe - Wish List': 'YouDescribe - Lista de desejos',
    'Author': 'Autor',
    'Published on': 'Publicado em',
    'Turn off descriptions for this video': 'Desligar a áudio descrição deste vídeo',
    'Turn off descriptions': 'Desligar áudio descrição',
    'Add a new description for this video': 'Adicionar uma nova áudio descrição para este vídeo',
    'Add description': 'Adicionar áudio descrição',
    'Turn on descriptions for this video': 'Ligar a áudio descrição deste vídeo',
    'Turn on descriptions': 'Ligar áudio descrição',
    'Selected description': 'Áudio descrição selecionada',
    "Rate this describer's audio description": 'Avalie a áudio descrição deste descritor',
    'Rate description': 'Avalie a áudio descrição',
    "Select this describer's audio description": 'Selecione a áudio descrição deste descritor',
    'Use description': 'Utilize esta áudio desrição',
    'Descriptions off': 'Áudio descrições desligadas',
    'Request an audio description for this video': 'Solicite uma áudio descrição para este vídeo',
    'Add to wish list': 'Adicionar na lista de desejos',
  },
  'pt-BR': {
    'RECENT DESCRIPTIONS': 'DESCRIÇÕES RECENTES',
    'WISH LIST': 'LISTA DE DESEJOS',
    HOME: 'INÍCIO',
    Close: 'Fechar',
    Search: 'Busca',
    Credits: 'Créditos',
    'Contact Us': 'Contato',
    Support: 'Suporte',
    'YouDescribe is a project of': 'YouDescribe é um projeto do',
    'Load more videos': 'Carregar mais vídeos',
    'Load more': 'Carregar mais',
    'Sign in with Google': 'Entrar com o Google',
    'All rights reserved': 'Todos os direitos reservados',
    'YouDescribe - Audio Description for YouTube Videos': 'YouDescribe - Áudio Descrição para vídeos do YouTube',
    'Search for a YouTube video. If a video with an audio description matching the search criteria exists, it will be available in the first section. If not, Youtube videos without audio descriptions matching the search criteria will be listed in the second section and requests for any of those videos can be made.': 'Busque por um vídeo do YouTube. Se um vídeo com audio descrição for encontrado, ele estará no primeiro bloco. Caso contrário estará no segundo bloco e você poderá solicitar uma audio descrição.',
    'You must sign in to perform this action': 'Você precisa estar logado para usar esse recurso',
    'You have to be logged in in order to vote': 'Você precisa estar logado para votar',
    'It was impossible to vote. Maybe your session has expired. Try to logout and login again.': 'Não foi possível votar. Tente logar novamente com seu usuário.',
    'YouDescribe - Authoring Tool': 'YouDescribe - Ferramenta de edição',
    'You have to be logged in in order to describe this video': 'Você precisa estar logado para poder descrever este vídeo',
    'Finish using your available record tracks': 'Termine de usar suas trilhas disponíveis',
    'You can just add more tracks when you finish recording the existing one': 'Você só pode adicionar mais trilhas quando terminar de usar as disponíveis',
    'Are you sure you want to remove this track? This action cannot be undone!': 'Você tem certeza que deseja apagar esta trilha? Não será possível desfazer essa ação',
    'Impossible to descrease the start time. It is already 0': 'Não é possível diminuir o tempo de início, pois já está em 0',
    'Impossible to increase the start time more': 'Não é possível aumentar mais o tempo de início',
    'Are you sure you want to change from EXTENDED to INLINE?': 'Você tem certeza que quer mudar de EXTENDIDA para LINEAR?',
    'Are you sure you want to change from INLINE to EXTENDED?': 'Você tem certeza que quer mudar de LINEAR para EXTENDIDA?',
    'You need to be logged in in order to record audio clips': 'Você precisa estar logado para gravar trilhas',
    'You need to stop recording in order to activate any other track': 'Você precisa parar sua gravação para ativar outra trilha',
    'Are you sure you wanna publish this audio description?': 'Você tem certeza que quer publicar essa áudio descrição?',
    'Are you sure you wanna unpublish this audio description?': 'Você tem certeza que quer despublicar essa áudio descrição?',
    'Are you sure you want to delete the audio description? This will remove all recorder tracks and cannot be undone': 'Você tem certeza que quer remover essa áudio descrição? Isso removerá todas as trilhas e não poderá ser desfeito',
    'Authoring is not available on this screen size. Please use a larger screen to add a description': 'A ferramenta de edição não está disponível para o seu tamanho de tela. Use uma resolução maior',
    'Loading': 'Carregando',
    'My descriptions': 'Minhas áudio descrições',
    'Unpublish': 'Despublicar',
    'Publish': 'Publicar',
    'Delete': 'Apagar',
    'Complete remove this audio description': 'Remove esta áudio descrição',
    'Unpublish this audio description for the current video': 'Despublicar esta áudio descrição',
    'Publish the video along with all audio description tracks': 'Publicar este vídeo com áudio descrição',
    'Save notes and labels anytime': 'Grava as notas e os títulos das trilhas',
    'Save': 'Gravar',
    "Add an inline audio description track which plays concurrently with the video's audio": "Adiciona uma trilha linear que irá ser reproduzida junto com o áudio do vídeo",
    'Add an extended audio description track which pauses the video as it plays and then resumes the video when it finishes': 'Adiciona uma trilha extendida que irá pausar o vídeo para ser reproduzida. Assim que terminar, o vídeo voltará a ser reproduzido',
    'YouDescribe - Wish List': 'YouDescribe - Lista de desejos',
    'Author': 'Autor',
    'Published on': 'Publicado em',
    'Turn off descriptions for this video': 'Desligar a áudio descrição deste vídeo',
    'Turn off descriptions': 'Desligar áudio descrição',
    'Add a new description for this video': 'Adicionar uma nova áudio descrição para este vídeo',
    'Add description': 'Adicionar áudio descrição',
    'Turn on descriptions for this video': 'Ligar a áudio descrição deste vídeo',
    'Turn on descriptions': 'Ligar áudio descrição',
    'Selected description': 'Áudio descrição selecionada',
    "Rate this describer's audio description": 'Avalie a áudio descrição deste descritor',
    'Rate description': 'Avalie a áudio descrição',
    "Select this describer's audio description": 'Selecione a áudio descrição deste descritor',
    'Use description': 'Utilize esta áudio desrição',
    'Descriptions off': 'Áudio descrições desligadas',
    'Request an audio description for this video': 'Solicite uma áudio descrição para este vídeo',
    'Add to wish list': 'Adicionar na lista de desejos',
  },
};

export default strings;
